server:
  port: 8080
  max-http-header-size: 16KB
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Book Service
      - id: book-service
        uri: lb://book-service
        predicates:
          - Path=/book/**
        filters:
          - RewritePath=/book/(?<path>.*), /$\{path}
          - AuthFilter

      - id: student-service
        uri: lb://student-service
        predicates:
          - Path=/student/**
        filters:
          - RewritePath=/student/(?<path>.*), /$\{path}
          - AuthFilter

      - id: auth-service
        uri: lb://auth-service
        predicates:
          - Path=/auth/**
        filters:
          - RewritePath=/auth/(?<path>.*), /$\{path}

      - id: openapi
        uri: http://${spring.application.name}:${server.port}
        predicates:
          - Path=/v3/api-docs/**
        filters:
          - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: Book Service
        url: /v3/api-docs/book
      - name: Student Service
        url: /v3/api-docs/student
      - name: Auth Service
        url: /v3/api-docs/auth

jwt:
  security:
    key: j3H5Ld5nYmGWyULy6xwpOgfSH++NgKXnJMq20vpfd+8=t