# service name
spring:
  application:
    name: auth-service
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: off
  datasource:

    url: jdbc:sqlserver://mssql:1433;databaseName=auth;trustServerCertificate=true;
    username: sa
    password: 1qazXSW@
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  # port
server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  # eureka server url
eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400