version: "3.9"
services:
  db:
    build:
      context: ./db-instance
      dockerfile: Dockerfile
    image:  ms/mssql-2019:latest
    container_name: mssql
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql/data
      - mssql_log:/var/opt/mssql/log
      - mssql_backup:/var/opt/mssql/backup
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#environment
    environment:
      # List of all SQL Server environment variables:
      # https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver15#environment-variables
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_SA_PASSWORD=1qazXSW@
  eureka-server:
    image: ms/eureka-server:latest
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
      args:
        - APP_NAME=eureka-server
        - APP_VERSION=0.0.1
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8761:8761"
  book-service:
    image: ms/book-service:latest
    container_name: book-service
    restart: on-failure
    build:
      context: ./book-service
      dockerfile: Dockerfile
      args:
        - APP_NAME=book-service
        - APP_VERSION=0.0.1
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    expose:
      - 8081
    depends_on:
      - db
      - eureka-server
  student-service:
    image: ms/student-service:latest
    container_name: student-service
    restart: on-failure
    build:
      context: ./student-service
      dockerfile: Dockerfile
      args:
        - APP_NAME=student-service
        - APP_VERSION=0.0.1
    #environment:
      #- eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    expose:
      - 8082
    depends_on:
      - db
      - eureka-server
  auth-service:
    image: ms/auth-service:latest
    container_name: auth-service
    restart: on-failure
    build:
      context: ./auth-service
      dockerfile: Dockerfile
      args:
        - APP_NAME=auth-service
        - APP_VERSION=0.0.1
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    expose:
      - 8083
    depends_on:
      - db
      - eureka-server
  gateway-server:
    image: ms/gateway-server:latest
    container_name: gateway-server
    restart: on-failure
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
      args:
        - APP_NAME=gateway-server
        - APP_VERSION=0.0.1
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    ports:
      - "8080:8080"
    depends_on:
      - db
      - auth-service
      - student-service
      - book-service
      - eureka-server

  # Create name volumes managed by Docker to not lose data when remove a container.
  # https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
volumes:
  mssql_data:
  mssql_log:
  mssql_backup: