# service name
spring:
  application:
    name: student-service
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: off
  datasource:
    url: jdbc:sqlserver://mssql:1433;databaseName=student;trustServerCertificate=true;
    username: sa
    password: 1qazXSW@
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  # port
server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  # eureka server url
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka